### ISSUE TITLE
Embed Colours

### ISSUE THREAD

**Issue by disqualified** [verixx/selfbot.py#103]
Verixx, could you make it so that there is an option to set embeds to random colours like -embedrandom so its not just gray and u dont have to do things like: -embed {color:#ac5aff} {title:This!}  to change the colours.

-LEAFY :DDDDDD

**Comment by fourjr** [comment]
Would be nice to also have a COLOR in config vars or something that overwrites dominant color in command embeds.

**Comment by verixx** [comment]
I'll make a seperate command `embedsay` where its used for quick embeds with random colors. Also the `COLOR` in config vars is a good idea.

**Comment by fourjr** [comment]
Added to latest version of selfbot.py I think
