### ISSUE TITLE
Make mute command have a duration 

### ISSUE THREAD

**Issue by h34422** [verixx/selfbot.py#105]
I don't know exactly how you would do this cause I have no knowledge of it but I'm suggesting making a command where you can mute and unmute people and have it so you can make it for how long they would be muted. 

Ex: .Mute (person) (time or no time)

**Comment by XAOS1502** [comment]
Doable, will try to implement

**Comment by fourjr** [comment]
Implemented https://github.com/verixx/selfbot.py/commit/7436f4b4bd1186e2d863ebbdf51d11cee6fb330f
