### ISSUE TITLE
add rotating playing command

### ISSUE THREAD

**Issue by OctoBubble** [verixx/selfbot.py#110]
This will rotate your now playing status next to your name

**Comment by fourjr** [comment]
[!image](https://vgy.me/Yf4fMJ.png)

**Comment by fourjr** [comment]
![Image](https://vgy.me/Yf4fMJ.png)
for some context from another selfbot

**Comment by OctoBubble** [comment]
![c12j5z](https://user-images.githubusercontent.com/20270765/32133998-0b60727a-bbe4-11e7-908d-8118d47318ec.gif)
Similar to this. (gif is a bit slow)

**Comment by PallavBS** [comment]
Copy paste into discord chat. statuses is the list of statuses.

r.eval
statuses = ['Hello there', 'this is another status']
# Add more game names here ^^

async def playing_task():
  while not bot.is_closed():
    for status in statuses:
      await asyncio.sleep(20)
      await bot.change_presence(game=discord.Game(name=status))

bot.loop.create_task(playing_task())

**Comment by fourjr** [comment]
Closed as discussion moved to #118
