### ISSUE TITLE
New commands for the selfbot that could be added

### ISSUE THREAD

**Issue by Garcia1008** [verixx/selfbot.py#121]
selfdestruct  -  Builds a self-destructing message. Ex: -sd 5
These command will self-destruct the last message you send. (Ignoring messages from other users)

whoisplaying- Check how many people are playing a certain game across all servers.
Example: !whoisplaying Clash Royale. 
These will print a list of the users playing cr. If they are more than 10-15 it could create a list in Gist

nickscan  -  Get a list of all your nicknames across all servers.
These will print an embed list will all the nicknames you have.

lockdown  -  Lock message sending in the channel.
If you have the perms. It will lockdown the channel for all the roles that are under you higher role

**Comment by fourjr** [comment]
No idea how to do selfdestruct :/

**Comment by XAOS1502** [comment]
what does it do!

**Comment by XAOS1502** [comment]
doing it as we speak

**Comment by XAOS1502** [comment]
Okay, no need for a new command, I added **selfdestruct** animation as pr

**Comment by Felixcoolguy** [comment]
What do you need to type to get it?

**Comment by fourjr** [comment]
All added, selfdestruct is an animation.
