### ISSUE TITLE
More Prefixes

### ISSUE THREAD

**Issue by Felixcoolguy** [verixx/selfbot.py#122]
This means people can have more than one prefix.

**Comment by fourjr** [comment]
making it a command wouldn't be easy since it'll require saving data. most likely will make another config variable if you want more prefixes

**Comment by Felixcoolguy** [comment]
Yes, that works too.

**Comment by verixx** [comment]
Why would you want more than one prefix though? Its a selfbot.
```py
@command.command()
async def prefix(self, ctx, *, prefix):
  os.environ['PREFIX'] = prefix
  await ctx.send(f'Changed prefix to: `{prefix}`')
```
Something like this would suffice.

**Comment by XAOS1502** [comment]
you need to know the prefix to use this command... since some people have no idea what their prefix is, how about `on_message` event to change the prefix temporarily? Or to show what prefix is set or default? Dunno, I just have seen enough people join and have no idea about their own prefix...

**Comment by Felixcoolguy** [comment]
By temporarily how long do you mean? XAOS1502

**Comment by XAOS1502** [comment]
Until Selfbot restarts...

**Comment by fourjr** [comment]
Don't see the absolute need in adding more prefixes, not something others would use either.
