### ISSUE TITLE
Follow Log

### ISSUE THREAD

**Issue by Garcia1008** [verixx/selfbot.py#34]
A log were u can set a user to follow and all messages that the user writes get stored in a private channel/server
Also if you set a word for Example: _Garcia_ all the messages in all your servers that contains the word _Garcia_ get stored in you channel/server

 (I copy the idea from appus selfbot).

**Comment by verixx** [comment]
Can you give command examples so i have a template to follow when i start writing the command / background task

**Comment by verixx** [comment]
Probably wont do this rn.
