### ISSUE TITLE
Rewrite help's second page prints empty

### ISSUE THREAD

**Issue by XAOS1502** [verixx/selfbot.py#68]
Just leaving this here so that at some point it can be fixed. I know the idea of the reactions to change pages was silly due to being a selfbot, so I have been thinking of ways to do it, and one that came to mind while working the lenny commands group was to have a help group as well.

That this would look like is something similar to:

`Input        .help`
`Output   First page of n pages`

`Input        .help 2`
`Output   Second page of n pages`

**Comment by verixx** [comment]
I fixed it finally.
